version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password  # MariaDB 루트 비밀번호
      MYSQL_DATABASE: your_database            # 기본 데이터베이스 이름
      MYSQL_USER: your_user                    # MariaDB 사용자 이름
      MYSQL_PASSWORD: your_password            # MariaDB 사용자 비밀번호
    volumes:
      - db_data:/var/lib/mysql                 # 데이터 저장을 위한 볼륨
    networks:
      - beeweb_shared-network

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_database
    expose:
      - "{port_num}"                                   # Node.js 내부에서 82번 포트를 사용
    ports:
      - "{port_num}:{port_num}"
    networks:
      - beeweb_shared-network

volumes:
  db_data:

networks:
  beeweb_shared-network:
    external: true
